"""
Add real vocabulary to existing lessons
"""
import asyncio
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.core.database import prisma
from dotenv import load_dotenv
import json

load_dotenv()

async def main():
    await prisma.connect()

    try:
        # Real vocabulary for each lesson
        lesson_vocab = {
            # Course 1: Alphabet
            "alef-bet-part-1": [
                {"hebrew": "א", "english": "alef", "transliteration": "alef"},
                {"hebrew": "ב", "english": "bet", "transliteration": "bet"},
                {"hebrew": "ג", "english": "gimel", "transliteration": "gimel"},
                {"hebrew": "ד", "english": "dalet", "transliteration": "dalet"},
                {"hebrew": "ה", "english": "hey", "transliteration": "hey"},
                {"hebrew": "ו", "english": "vav", "transliteration": "vav"},
                {"hebrew": "ז", "english": "zayin", "transliteration": "zayin"},
                {"hebrew": "ח", "english": "chet", "transliteration": "chet"},
                {"hebrew": "ט", "english": "tet", "transliteration": "tet"},
                {"hebrew": "י", "english": "yod", "transliteration": "yod"},
                {"hebrew": "כ", "english": "kaf", "transliteration": "kaf"},
                {"hebrew": "ל", "english": "lamed", "transliteration": "lamed"},
                {"hebrew": "מ", "english": "mem", "transliteration": "mem"},
                {"hebrew": "נ", "english": "nun", "transliteration": "nun"},
                {"hebrew": "ס", "english": "samech", "transliteration": "samech"},
                {"hebrew": "ע", "english": "ayin", "transliteration": "ayin"},
                {"hebrew": "פ", "english": "pey", "transliteration": "pey"},
                {"hebrew": "צ", "english": "tsadi", "transliteration": "tsadi"},
                {"hebrew": "ק", "english": "kuf", "transliteration": "kuf"},
                {"hebrew": "ר", "english": "resh", "transliteration": "resh"},
                {"hebrew": "ש", "english": "shin", "transliteration": "shin"},
                {"hebrew": "ת", "english": "tav", "transliteration": "tav"},
            ],
            "vowels-final-forms": [
                {"hebrew": "ך", "english": "final kaf", "transliteration": "kaf sofit"},
                {"hebrew": "ם", "english": "final mem", "transliteration": "mem sofit"},
                {"hebrew": "ן", "english": "final nun", "transliteration": "nun sofit"},
                {"hebrew": "ף", "english": "final pey", "transliteration": "pey sofit"},
                {"hebrew": "ץ", "english": "final tsadi", "transliteration": "tsadi sofit"},
                {"hebrew": "ַ", "english": "patach (a)", "transliteration": "patach"},
                {"hebrew": "ָ", "english": "kamatz (a)", "transliteration": "kamatz"},
                {"hebrew": "ֶ", "english": "segol (e)", "transliteration": "segol"},
                {"hebrew": "ֵ", "english": "tsere (e)", "transliteration": "tsere"},
                {"hebrew": "ִ", "english": "chirik (i)", "transliteration": "chirik"},
                {"hebrew": "ֹ", "english": "cholam (o)", "transliteration": "cholam"},
                {"hebrew": "ֻ", "english": "kubutz (u)", "transliteration": "kubutz"},
                {"hebrew": "ְ", "english": "shva (silent/e)", "transliteration": "shva"},
            ],

            # Course 2: Greetings
            "essential-greetings": [
                {"hebrew": "שָׁלוֹם", "english": "hello/peace", "transliteration": "shalom"},
                {"hebrew": "בֹּקֶר טוֹב", "english": "good morning", "transliteration": "boker tov"},
                {"hebrew": "עֶרֶב טוֹב", "english": "good evening", "transliteration": "erev tov"},
                {"hebrew": "לַיְלָה טוֹב", "english": "good night", "transliteration": "layla tov"},
                {"hebrew": "תּוֹדָה", "english": "thank you", "transliteration": "toda"},
                {"hebrew": "בְּבַקָּשָׁה", "english": "please", "transliteration": "bevakasha"},
                {"hebrew": "כֵּן", "english": "yes", "transliteration": "ken"},
                {"hebrew": "לֹא", "english": "no", "transliteration": "lo"},
                {"hebrew": "מַה נִּשְׁמָע", "english": "what's up/how are you", "transliteration": "ma nishma"},
                {"hebrew": "בְּסֵדֶר", "english": "okay/fine", "transliteration": "beseder"},
                {"hebrew": "טוֹב", "english": "good", "transliteration": "tov"},
                {"hebrew": "לְהִתְרָאוֹת", "english": "goodbye", "transliteration": "lehitraot"},
                {"hebrew": "שַׁבָּת שָׁלוֹם", "english": "peaceful Sabbath", "transliteration": "shabbat shalom"},
                {"hebrew": "חַג שָׂמֵחַ", "english": "happy holiday", "transliteration": "chag sameach"},
                {"hebrew": "מָה הַמַּצָּב", "english": "how's it going", "transliteration": "ma hamatzav"},
            ],
            "introductions": [
                {"hebrew": "שְׁמִי", "english": "my name is", "transliteration": "shmi"},
                {"hebrew": "מַה שִּׁמְךָ", "english": "what's your name (m)", "transliteration": "ma shimcha"},
                {"hebrew": "מַה שְּׁמֵךְ", "english": "what's your name (f)", "transliteration": "ma shmech"},
                {"hebrew": "נָעִים מְאוֹד", "english": "nice to meet you", "transliteration": "naim meod"},
                {"hebrew": "אֲנִי מִ", "english": "I'm from", "transliteration": "ani mi"},
                {"hebrew": "מֵאֵיפֹה אַתָּה", "english": "where are you from (m)", "transliteration": "meeifo ata"},
                {"hebrew": "מֵאֵיפֹה אַתְּ", "english": "where are you from (f)", "transliteration": "meeifo at"},
                {"hebrew": "אֲנִי", "english": "I", "transliteration": "ani"},
                {"hebrew": "אַתָּה", "english": "you (m)", "transliteration": "ata"},
                {"hebrew": "אַתְּ", "english": "you (f)", "transliteration": "at"},
                {"hebrew": "אָמֶרִיקָה", "english": "America", "transliteration": "amerika"},
                {"hebrew": "יִשְׂרָאֵל", "english": "Israel", "transliteration": "yisrael"},
                {"hebrew": "אַנְגְּלִיָּה", "english": "England", "transliteration": "angliya"},
                {"hebrew": "צָרְפַת", "english": "France", "transliteration": "tzarfat"},
                {"hebrew": "גֶּרְמַנְיָה", "english": "Germany", "transliteration": "germania"},
                {"hebrew": "גָּר", "english": "live/reside (m)", "transliteration": "gar"},
                {"hebrew": "גָּרָה", "english": "live/reside (f)", "transliteration": "gara"},
                {"hebrew": "עוֹבֵד", "english": "work (m)", "transliteration": "oved"},
                {"hebrew": "עוֹבֶדֶת", "english": "work (f)", "transliteration": "ovedet"},
                {"hebrew": "לוֹמֵד", "english": "study (m)", "transliteration": "lomed"},
            ],
            "polite-expressions": [
                {"hebrew": "סְלִיחָה", "english": "sorry/excuse me", "transliteration": "slicha"},
                {"hebrew": "אֵין בְּעַד מָה", "english": "you're welcome", "transliteration": "ein be'ad ma"},
                {"hebrew": "תּוֹדָה רַבָּה", "english": "thank you very much", "transliteration": "toda raba"},
                {"hebrew": "סַלֵּחַ לִי", "english": "forgive me", "transliteration": "salach li"},
                {"hebrew": "בְּבַקָּשָׁה", "english": "please", "transliteration": "bevakasha"},
                {"hebrew": "אַל דָּאֲגָה", "english": "don't worry", "transliteration": "al da'aga"},
                {"hebrew": "בְּשִׂמְחָה", "english": "with pleasure", "transliteration": "besimcha"},
                {"hebrew": "מָזָל טוֹב", "english": "congratulations", "transliteration": "mazal tov"},
                {"hebrew": "רְפוּאָה שְׁלֵמָה", "english": "full recovery/get well", "transliteration": "refuah shlema"},
                {"hebrew": "בְּהַצְלָחָה", "english": "good luck", "transliteration": "behatzlacha"},
                {"hebrew": "שָׁנָה טוֹבָה", "english": "happy new year", "transliteration": "shana tova"},
                {"hebrew": "יוֹם הוּלֶּדֶת שָׂמֵחַ", "english": "happy birthday", "transliteration": "yom huledet sameach"},
                {"hebrew": "לְאַט", "english": "slowly", "transliteration": "le'at"},
                {"hebrew": "אֶפְשָׁר", "english": "possible/may I", "transliteration": "efshar"},
                {"hebrew": "מַמָּשׁ", "english": "really/very", "transliteration": "mamash"},
                {"hebrew": "בְּבַקָּשָׁה תְּדַבֵּר לְאַט", "english": "please speak slowly", "transliteration": "bevakasha tedaber le'at"},
                {"hebrew": "אֲנִי לֹא מֵבִין", "english": "I don't understand (m)", "transliteration": "ani lo mevin"},
                {"hebrew": "אֲנִי לֹא מְבִינָה", "english": "I don't understand (f)", "transliteration": "ani lo mevina"},
                {"hebrew": "סַבָּא", "english": "grandfather", "transliteration": "saba"},
                {"hebrew": "מָה זֶה", "english": "what is this", "transliteration": "ma ze"},
            ],

            # Course 3: Numbers & Time
            "numbers-1-20": [
                {"hebrew": "אֶחָד", "english": "one (m)", "transliteration": "echad"},
                {"hebrew": "אַחַת", "english": "one (f)", "transliteration": "achat"},
                {"hebrew": "שְׁנַיִם", "english": "two (m)", "transliteration": "shnayim"},
                {"hebrew": "שְׁתַּיִם", "english": "two (f)", "transliteration": "shtayim"},
                {"hebrew": "שְׁלוֹשָׁה", "english": "three (m)", "transliteration": "shlosha"},
                {"hebrew": "שָׁלוֹשׁ", "english": "three (f)", "transliteration": "shalosh"},
                {"hebrew": "אַרְבָּעָה", "english": "four (m)", "transliteration": "arba'a"},
                {"hebrew": "אַרְבַּע", "english": "four (f)", "transliteration": "arba"},
                {"hebrew": "חֲמִשָּׁה", "english": "five (m)", "transliteration": "chamisha"},
                {"hebrew": "חָמֵשׁ", "english": "five (f)", "transliteration": "chamesh"},
                {"hebrew": "שִׁשָּׁה", "english": "six (m)", "transliteration": "shisha"},
                {"hebrew": "שֵׁשׁ", "english": "six (f)", "transliteration": "shesh"},
                {"hebrew": "שִׁבְעָה", "english": "seven (m)", "transliteration": "shiv'a"},
                {"hebrew": "שֶׁבַע", "english": "seven (f)", "transliteration": "sheva"},
                {"hebrew": "שְׁמוֹנָה", "english": "eight (m)", "transliteration": "shmona"},
                {"hebrew": "שְׁמוֹנֶה", "english": "eight (f)", "transliteration": "shmone"},
                {"hebrew": "תִּשְׁעָה", "english": "nine (m)", "transliteration": "tish'a"},
                {"hebrew": "תֵּשַׁע", "english": "nine (f)", "transliteration": "tesha"},
                {"hebrew": "עֲשָׂרָה", "english": "ten (m)", "transliteration": "asara"},
                {"hebrew": "עֶשֶׂר", "english": "ten (f)", "transliteration": "eser"},
            ],
            "numbers-20-1000": [
                {"hebrew": "עֶשְׂרִים", "english": "twenty", "transliteration": "esrim"},
                {"hebrew": "שְׁלוֹשִׁים", "english": "thirty", "transliteration": "shloshim"},
                {"hebrew": "אַרְבָּעִים", "english": "forty", "transliteration": "arba'im"},
                {"hebrew": "חֲמִשִּׁים", "english": "fifty", "transliteration": "chamishim"},
                {"hebrew": "שִׁשִּׁים", "english": "sixty", "transliteration": "shishim"},
                {"hebrew": "שִׁבְעִים", "english": "seventy", "transliteration": "shiv'im"},
                {"hebrew": "שְׁמוֹנִים", "english": "eighty", "transliteration": "shmonim"},
                {"hebrew": "תִּשְׁעִים", "english": "ninety", "transliteration": "tish'im"},
                {"hebrew": "מֵאָה", "english": "hundred", "transliteration": "me'a"},
                {"hebrew": "מָאתַיִם", "english": "two hundred", "transliteration": "matayim"},
                {"hebrew": "אֶלֶף", "english": "thousand", "transliteration": "elef"},
                {"hebrew": "מִלְיוֹן", "english": "million", "transliteration": "milyon"},
                {"hebrew": "כַּמָּה", "english": "how much/many", "transliteration": "kama"},
                {"hebrew": "מִסְפָּר", "english": "number", "transliteration": "mispar"},
                {"hebrew": "שֶׁקֶל", "english": "shekel", "transliteration": "shekel"},
            ],
            "time-clock": [
                {"hebrew": "שָׁעָה", "english": "hour/clock", "transliteration": "sha'a"},
                {"hebrew": "דַּקָּה", "english": "minute", "transliteration": "daka"},
                {"hebrew": "שְׁנִיָּה", "english": "second", "transliteration": "shniya"},
                {"hebrew": "מַה הַשָּׁעָה", "english": "what time is it", "transliteration": "ma hasha'a"},
                {"hebrew": "בֹּקֶר", "english": "morning", "transliteration": "boker"},
                {"hebrew": "צָהֳרַיִם", "english": "noon", "transliteration": "tzohorayim"},
                {"hebrew": "אַחַר הַצָּהֳרַיִם", "english": "afternoon", "transliteration": "achar hatzohorayim"},
                {"hebrew": "עֶרֶב", "english": "evening", "transliteration": "erev"},
                {"hebrew": "לַיְלָה", "english": "night", "transliteration": "layla"},
                {"hebrew": "חֲצוֹת", "english": "midnight", "transliteration": "chatzot"},
                {"hebrew": "עַכְשָׁיו", "english": "now", "transliteration": "achshav"},
                {"hebrew": "מְאֻחָר", "english": "late", "transliteration": "me'uchar"},
                {"hebrew": "מוּקְדָּם", "english": "early", "transliteration": "mukdam"},
                {"hebrew": "בְּעוֹד", "english": "in (time)", "transliteration": "be'od"},
                {"hebrew": "רֶבַע", "english": "quarter", "transliteration": "reva"},
                {"hebrew": "חֵצִי", "english": "half", "transliteration": "chetzi"},
                {"hebrew": "פְּגִישָׁה", "english": "meeting/appointment", "transliteration": "pgisha"},
                {"hebrew": "מָתַי", "english": "when", "transliteration": "matay"},
                {"hebrew": "זְמַן", "english": "time", "transliteration": "zman"},
                {"hebrew": "שָׁבוּעַ", "english": "week", "transliteration": "shavua"},
            ],
            "days-months-seasons": [
                {"hebrew": "יוֹם", "english": "day", "transliteration": "yom"},
                {"hebrew": "יוֹם רִאשׁוֹן", "english": "Sunday", "transliteration": "yom rishon"},
                {"hebrew": "יוֹם שֵׁנִי", "english": "Monday", "transliteration": "yom sheni"},
                {"hebrew": "יוֹם שְׁלִישִׁי", "english": "Tuesday", "transliteration": "yom shlishi"},
                {"hebrew": "יוֹם רְבִיעִי", "english": "Wednesday", "transliteration": "yom revi'i"},
                {"hebrew": "יוֹם חֲמִישִׁי", "english": "Thursday", "transliteration": "yom chamishi"},
                {"hebrew": "יוֹם שִׁשִּׁי", "english": "Friday", "transliteration": "yom shishi"},
                {"hebrew": "שַׁבָּת", "english": "Saturday/Sabbath", "transliteration": "shabbat"},
                {"hebrew": "הַיּוֹם", "english": "today", "transliteration": "hayom"},
                {"hebrew": "מָחָר", "english": "tomorrow", "transliteration": "machar"},
                {"hebrew": "אֶתְמוֹל", "english": "yesterday", "transliteration": "etmol"},
                {"hebrew": "חֹדֶשׁ", "english": "month", "transliteration": "chodesh"},
                {"hebrew": "שָׁנָה", "english": "year", "transliteration": "shana"},
                {"hebrew": "תָּאֲרִיךְ", "english": "date", "transliteration": "ta'arich"},
                {"hebrew": "לוּחַ שָׁנָה", "english": "calendar", "transliteration": "luach shana"},
            ],

            # Course 4: Family
            "immediate-family": [
                {"hebrew": "מִשְׁפָּחָה", "english": "family", "transliteration": "mishpacha"},
                {"hebrew": "אָב", "english": "father", "transliteration": "av"},
                {"hebrew": "אַבָּא", "english": "dad", "transliteration": "abba"},
                {"hebrew": "אֵם", "english": "mother", "transliteration": "em"},
                {"hebrew": "אִמָּא", "english": "mom", "transliteration": "ima"},
                {"hebrew": "הוֹרִים", "english": "parents", "transliteration": "horim"},
                {"hebrew": "בֵּן", "english": "son", "transliteration": "ben"},
                {"hebrew": "בַּת", "english": "daughter", "transliteration": "bat"},
                {"hebrew": "יְלָדִים", "english": "children", "transliteration": "yeladim"},
                {"hebrew": "אָח", "english": "brother", "transliteration": "ach"},
                {"hebrew": "אָחוֹת", "english": "sister", "transliteration": "achot"},
                {"hebrew": "בַּעַל", "english": "husband", "transliteration": "ba'al"},
                {"hebrew": "אִשָּׁה", "english": "wife", "transliteration": "isha"},
                {"hebrew": "בַּיִת", "english": "home/house", "transliteration": "bayit"},
                {"hebrew": "אֱנוֹשׁ", "english": "person", "transliteration": "enosh"},
                {"hebrew": "גֶּבֶר", "english": "man", "transliteration": "gever"},
                {"hebrew": "אִישׁ", "english": "man/husband", "transliteration": "ish"},
                {"hebrew": "תִּינוֹק", "english": "baby", "transliteration": "tinok"},
                {"hebrew": "יֶלֶד", "english": "boy/child", "transliteration": "yeled"},
                {"hebrew": "יַלְדָּה", "english": "girl", "transliteration": "yalda"},
            ],
            "extended-family": [
                {"hebrew": "סָבָא", "english": "grandfather", "transliteration": "saba"},
                {"hebrew": "סָבְתָא", "english": "grandmother", "transliteration": "savta"},
                {"hebrew": "דּוֹד", "english": "uncle", "transliteration": "dod"},
                {"hebrew": "דּוֹדָה", "english": "aunt", "transliteration": "doda"},
                {"hebrew": "בֶּן דּוֹד", "english": "cousin (m)", "transliteration": "ben dod"},
                {"hebrew": "בַּת דּוֹדָה", "english": "cousin (f)", "transliteration": "bat doda"},
                {"hebrew": "נֶכֶד", "english": "grandson", "transliteration": "neched"},
                {"hebrew": "נֶכְדָּה", "english": "granddaughter", "transliteration": "nechda"},
                {"hebrew": "חָם", "english": "father-in-law", "transliteration": "cham"},
                {"hebrew": "חָמוֹת", "english": "mother-in-law", "transliteration": "chamot"},
                {"hebrew": "גִּיס", "english": "brother-in-law", "transliteration": "gis"},
                {"hebrew": "גִּיסָה", "english": "sister-in-law", "transliteration": "gisa"},
                {"hebrew": "קָרוֹב", "english": "relative/close", "transliteration": "karov"},
                {"hebrew": "קְרוֹבִים", "english": "relatives", "transliteration": "krovim"},
                {"hebrew": "דּוֹר", "english": "generation", "transliteration": "dor"},
            ],

            # Course 5: Body & Feelings
            "body-parts": [
                {"hebrew": "רֹאשׁ", "english": "head", "transliteration": "rosh"},
                {"hebrew": "שֵׂעָר", "english": "hair", "transliteration": "se'ar"},
                {"hebrew": "פָּנִים", "english": "face", "transliteration": "panim"},
                {"hebrew": "עַיִן", "english": "eye", "transliteration": "ayin"},
                {"hebrew": "עֵינַיִם", "english": "eyes", "transliteration": "einayim"},
                {"hebrew": "אֹזֶן", "english": "ear", "transliteration": "ozen"},
                {"hebrew": "אָף", "english": "nose", "transliteration": "af"},
                {"hebrew": "פֶּה", "english": "mouth", "transliteration": "pe"},
                {"hebrew": "שֵׁן", "english": "tooth", "transliteration": "shen"},
                {"hebrew": "לָשׁוֹן", "english": "tongue", "transliteration": "lashon"},
                {"hebrew": "צַוָּאר", "english": "neck", "transliteration": "tzavar"},
                {"hebrew": "כָּתֵף", "english": "shoulder", "transliteration": "katef"},
                {"hebrew": "יָד", "english": "hand/arm", "transliteration": "yad"},
                {"hebrew": "אֶצְבַּע", "english": "finger", "transliteration": "etzba"},
                {"hebrew": "רֶגֶל", "english": "leg/foot", "transliteration": "regel"},
                {"hebrew": "בֶּטֶן", "english": "stomach/belly", "transliteration": "beten"},
                {"hebrew": "גַּב", "english": "back", "transliteration": "gav"},
                {"hebrew": "לֵב", "english": "heart", "transliteration": "lev"},
                {"hebrew": "גּוּף", "english": "body", "transliteration": "guf"},
                {"hebrew": "בְּרִיא", "english": "healthy", "transliteration": "bari"},
            ],
            "feelings-emotions": [
                {"hebrew": "שָׂמֵחַ", "english": "happy (m)", "transliteration": "sameach"},
                {"hebrew": "שְׂמֵחָה", "english": "happy (f)", "transliteration": "smecha"},
                {"hebrew": "עָצוּב", "english": "sad (m)", "transliteration": "atzuv"},
                {"hebrew": "עֲצוּבָה", "english": "sad (f)", "transliteration": "atzuva"},
                {"hebrew": "כּוֹעֵס", "english": "angry (m)", "transliteration": "ko'es"},
                {"hebrew": "כּוֹעֶסֶת", "english": "angry (f)", "transliteration": "ko'eset"},
                {"hebrew": "מְפַחֵד", "english": "scared (m)", "transliteration": "mefached"},
                {"hebrew": "מְפַחֶדֶת", "english": "scared (f)", "transliteration": "mefachedet"},
                {"hebrew": "אוֹהֵב", "english": "love (m)", "transliteration": "ohev"},
                {"hebrew": "אוֹהֶבֶת", "english": "love (f)", "transliteration": "ohevet"},
                {"hebrew": "אַהֲבָה", "english": "love (noun)", "transliteration": "ahava"},
                {"hebrew": "עַיֵּף", "english": "tired (m)", "transliteration": "ayef"},
                {"hebrew": "עֲיֵפָה", "english": "tired (f)", "transliteration": "ayefa"},
                {"hebrew": "רָעֵב", "english": "hungry (m)", "transliteration": "ra'ev"},
                {"hebrew": "רְעֵבָה", "english": "hungry (f)", "transliteration": "re'eva"},
                {"hebrew": "צָמֵא", "english": "thirsty (m)", "transliteration": "tzame"},
                {"hebrew": "צְמֵאָה", "english": "thirsty (f)", "transliteration": "tzme'a"},
                {"hebrew": "מְאֻשָּׁר", "english": "very happy (m)", "transliteration": "me'ushar"},
                {"hebrew": "רָגוּעַ", "english": "calm (m)", "transliteration": "ragu'a"},
                {"hebrew": "לֹחוּץ", "english": "stressed (m)", "transliteration": "lachutz"},
            ],

            # Course 6: Daily Life
            "daily-routine-verbs": [
                {"hebrew": "קָם", "english": "wake up/get up (m)", "transliteration": "kam"},
                {"hebrew": "קָמָה", "english": "wake up/get up (f)", "transliteration": "kama"},
                {"hebrew": "יָשֵׁן", "english": "sleep (m)", "transliteration": "yashen"},
                {"hebrew": "יְשֵׁנָה", "english": "sleep (f)", "transliteration": "yeshena"},
                {"hebrew": "אוֹכֵל", "english": "eat (m)", "transliteration": "ochel"},
                {"hebrew": "אוֹכֶלֶת", "english": "eat (f)", "transliteration": "ochelet"},
                {"hebrew": "שׁוֹתֶה", "english": "drink (m)", "transliteration": "shote"},
                {"hebrew": "שׁוֹתָה", "english": "drink (f)", "transliteration": "shota"},
                {"hebrew": "רוֹחֵץ", "english": "shower/wash (m)", "transliteration": "rochetz"},
                {"hebrew": "רוֹחֶצֶת", "english": "shower/wash (f)", "transliteration": "rochetzet"},
                {"hebrew": "לוֹבֵשׁ", "english": "wear/dress (m)", "transliteration": "lovesh"},
                {"hebrew": "לוֹבֶשֶׁת", "english": "wear/dress (f)", "transliteration": "loveshet"},
                {"hebrew": "הוֹלֵךְ", "english": "go/walk (m)", "transliteration": "holech"},
                {"hebrew": "הוֹלֶכֶת", "english": "go/walk (f)", "transliteration": "holechet"},
                {"hebrew": "עוֹבֵד", "english": "work (m)", "transliteration": "oved"},
                {"hebrew": "עוֹבֶדֶת", "english": "work (f)", "transliteration": "ovedet"},
                {"hebrew": "לוֹמֵד", "english": "study/learn (m)", "transliteration": "lomed"},
                {"hebrew": "לוֹמֶדֶת", "english": "study/learn (f)", "transliteration": "lomedet"},
                {"hebrew": "חוֹזֵר", "english": "return (m)", "transliteration": "chozer"},
                {"hebrew": "חוֹזֶרֶת", "english": "return (f)", "transliteration": "chozeret"},
            ],
            "home-house": [
                {"hebrew": "בַּיִת", "english": "house/home", "transliteration": "bayit"},
                {"hebrew": "דִּירָה", "english": "apartment", "transliteration": "dira"},
                {"hebrew": "חֶדֶר", "english": "room", "transliteration": "cheder"},
                {"hebrew": "חֶדֶר שֵׁנָה", "english": "bedroom", "transliteration": "cheder shena"},
                {"hebrew": "סָלוֹן", "english": "living room", "transliteration": "salon"},
                {"hebrew": "מִטְבָּח", "english": "kitchen", "transliteration": "mitbach"},
                {"hebrew": "אַמְבַּטְיָה", "english": "bathroom", "transliteration": "ambatya"},
                {"hebrew": "שֵׁרוּתִים", "english": "toilet/restroom", "transliteration": "sherutim"},
                {"hebrew": "מִרְפֶּסֶת", "english": "balcony", "transliteration": "mirpeset"},
                {"hebrew": "גִּנָּה", "english": "garden", "transliteration": "gina"},
                {"hebrew": "דֶּלֶת", "english": "door", "transliteration": "delet"},
                {"hebrew": "חַלּוֹן", "english": "window", "transliteration": "chalon"},
                {"hebrew": "קִיר", "english": "wall", "transliteration": "kir"},
                {"hebrew": "רִצְפָּה", "english": "floor", "transliteration": "ritzpa"},
                {"hebrew": "תִּקְרָה", "english": "ceiling", "transliteration": "tikra"},
            ],

            # Course 7: Food
            "basic-foods": [
                {"hebrew": "לֶחֶם", "english": "bread", "transliteration": "lechem"},
                {"hebrew": "חָלָב", "english": "milk", "transliteration": "chalav"},
                {"hebrew": "גְּבִינָה", "english": "cheese", "transliteration": "gvina"},
                {"hebrew": "בֵּיצָה", "english": "egg", "transliteration": "beitza"},
                {"hebrew": "בָּשָׂר", "english": "meat", "transliteration": "basar"},
                {"hebrew": "דָּג", "english": "fish", "transliteration": "dag"},
                {"hebrew": "עוֹף", "english": "chicken/poultry", "transliteration": "of"},
                {"hebrew": "אֹרֶז", "english": "rice", "transliteration": "orez"},
                {"hebrew": "פַּסְטָה", "english": "pasta", "transliteration": "pasta"},
                {"hebrew": "סָלָט", "english": "salad", "transliteration": "salat"},
                {"hebrew": "מָרָק", "english": "soup", "transliteration": "marak"},
                {"hebrew": "חֶמְאָה", "english": "butter", "transliteration": "chem'a"},
                {"hebrew": "שֶׁמֶן", "english": "oil", "transliteration": "shemen"},
                {"hebrew": "מֶלַח", "english": "salt", "transliteration": "melach"},
                {"hebrew": "פִּלְפֵּל", "english": "pepper", "transliteration": "pilpel"},
                {"hebrew": "סֻכָּר", "english": "sugar", "transliteration": "sukar"},
                {"hebrew": "טָעִים", "english": "tasty/delicious", "transliteration": "ta'im"},
                {"hebrew": "אוֹכֶל", "english": "food", "transliteration": "ochel"},
                {"hebrew": "אֲרוּחָה", "english": "meal", "transliteration": "arucha"},
                {"hebrew": "בְּתֵאָבוֹן", "english": "bon appetit", "transliteration": "beteavon"},
            ],
            "drinks-beverages": [
                {"hebrew": "מַיִם", "english": "water", "transliteration": "mayim"},
                {"hebrew": "קָפֶה", "english": "coffee", "transliteration": "kafe"},
                {"hebrew": "תֵּה", "english": "tea", "transliteration": "te"},
                {"hebrew": "מִיץ", "english": "juice", "transliteration": "mitz"},
                {"hebrew": "סוֹדָה", "english": "soda", "transliteration": "soda"},
                {"hebrew": "קוֹלָה", "english": "cola", "transliteration": "kola"},
                {"hebrew": "בִּירָה", "english": "beer", "transliteration": "bira"},
                {"hebrew": "יַיִן", "english": "wine", "transliteration": "yayin"},
                {"hebrew": "שֵׁכָר", "english": "alcohol/beer", "transliteration": "shechar"},
                {"hebrew": "מַשְׁקֶה", "english": "drink/beverage", "transliteration": "mashke"},
                {"hebrew": "חַם", "english": "hot", "transliteration": "cham"},
                {"hebrew": "קַר", "english": "cold", "transliteration": "kar"},
                {"hebrew": "קָרָח", "english": "ice", "transliteration": "kerach"},
                {"hebrew": "עִם סֻכָּר", "english": "with sugar", "transliteration": "im sukar"},
                {"hebrew": "בְּלִי סֻכָּר", "english": "without sugar", "transliteration": "bli sukar"},
            ],
            "fruits-vegetables": [
                {"hebrew": "תַּפּוּחַ", "english": "apple", "transliteration": "tapuach"},
                {"hebrew": "בָּנָנָה", "english": "banana", "transliteration": "banana"},
                {"hebrew": "תַּפּוּז", "english": "orange", "transliteration": "tapuz"},
                {"hebrew": "עֲנָבִים", "english": "grapes", "transliteration": "anavim"},
                {"hebrew": "אֲבַטִּיחַ", "english": "watermelon", "transliteration": "avatiach"},
                {"hebrew": "אֲגַס", "english": "pear", "transliteration": "agas"},
                {"hebrew": "תּוּת", "english": "strawberry", "transliteration": "tut"},
                {"hebrew": "עֲגָבַנִיָּה", "english": "tomato", "transliteration": "agvaniya"},
                {"hebrew": "מֶלָפְפוֹן", "english": "cucumber", "transliteration": "melafefon"},
                {"hebrew": "גֶּזֶר", "english": "carrot", "transliteration": "gezer"},
                {"hebrew": "בָּצָל", "english": "onion", "transliteration": "batzal"},
                {"hebrew": "שׁוּם", "english": "garlic", "transliteration": "shum"},
                {"hebrew": "חֲסָה", "english": "lettuce", "transliteration": "chasa"},
                {"hebrew": "פֶּרִי", "english": "fruit", "transliteration": "peri"},
                {"hebrew": "יָרָק", "english": "vegetable", "transliteration": "yarak"},
            ],

            # Course 8: Shopping
            "shopping-vocabulary": [
                {"hebrew": "חֲנוּת", "english": "store/shop", "transliteration": "chanut"},
                {"hebrew": "סוּפֶּרְמַרְקֵט", "english": "supermarket", "transliteration": "supermarket"},
                {"hebrew": "קוֹנֶה", "english": "buy (m)", "transliteration": "kone"},
                {"hebrew": "קוֹנָה", "english": "buy (f)", "transliteration": "kona"},
                {"hebrew": "מוֹכֵר", "english": "sell (m)", "transliteration": "mocher"},
                {"hebrew": "מוֹכֶרֶת", "english": "sell (f)", "transliteration": "mocheret"},
                {"hebrew": "כֶּסֶף", "english": "money", "transliteration": "kesef"},
                {"hebrew": "מְחִיר", "english": "price", "transliteration": "mechir"},
                {"hebrew": "כַּמָּה זֶה עוֹלֶה", "english": "how much does it cost", "transliteration": "kama ze ole"},
                {"hebrew": "יָקָר", "english": "expensive", "transliteration": "yakar"},
                {"hebrew": "זוֹל", "english": "cheap", "transliteration": "zol"},
                {"hebrew": "הֲנָחָה", "english": "discount/sale", "transliteration": "hanacha"},
                {"hebrew": "לְשַׁלֵּם", "english": "to pay", "transliteration": "leshalem"},
                {"hebrew": "כַּרְטִיס אַשְׁרַאי", "english": "credit card", "transliteration": "kartis ashrai"},
                {"hebrew": "מְזֻמָּן", "english": "cash", "transliteration": "mezuman"},
                {"hebrew": "קַבָּלָה", "english": "receipt", "transliteration": "kabala"},
                {"hebrew": "שַׂק", "english": "bag", "transliteration": "sak"},
                {"hebrew": "עֲגָלָה", "english": "shopping cart", "transliteration": "agala"},
                {"hebrew": "רוֹצֶה", "english": "want (m)", "transliteration": "rotze"},
                {"hebrew": "רוֹצָה", "english": "want (f)", "transliteration": "rotza"},
            ],
            "clothing-colors": [
                {"hebrew": "בֶּגֶד", "english": "clothing item", "transliteration": "beged"},
                {"hebrew": "חוּלְצָה", "english": "shirt", "transliteration": "chultza"},
                {"hebrew": "מִכְנָסַיִם", "english": "pants", "transliteration": "michnasayim"},
                {"hebrew": "שִׂמְלָה", "english": "dress", "transliteration": "simla"},
                {"hebrew": "נַעֲלַיִם", "english": "shoes", "transliteration": "na'alayim"},
                {"hebrew": "גַּרְבַּיִם", "english": "socks", "transliteration": "garbayim"},
                {"hebrew": "אָדֹם", "english": "red", "transliteration": "adom"},
                {"hebrew": "כָּחֹל", "english": "blue", "transliteration": "kachol"},
                {"hebrew": "יָרֹק", "english": "green", "transliteration": "yarok"},
                {"hebrew": "צָהֹב", "english": "yellow", "transliteration": "tzahov"},
                {"hebrew": "לָבָן", "english": "white", "transliteration": "lavan"},
                {"hebrew": "שָׁחֹר", "english": "black", "transliteration": "shachor"},
                {"hebrew": "כָּתֹם", "english": "orange", "transliteration": "katom"},
                {"hebrew": "סָגֹל", "english": "purple", "transliteration": "sagol"},
                {"hebrew": "חוּם", "english": "brown", "transliteration": "chum"},
                {"hebrew": "אָפֹר", "english": "gray", "transliteration": "afor"},
                {"hebrew": "צֶבַע", "english": "color", "transliteration": "tzeva"},
                {"hebrew": "גֹּדֶל", "english": "size", "transliteration": "godel"},
                {"hebrew": "קָטָן", "english": "small", "transliteration": "katan"},
                {"hebrew": "גָּדוֹל", "english": "big", "transliteration": "gadol"},
            ],

            # Course 9: Places
            "places-in-city": [
                {"hebrew": "עִיר", "english": "city", "transliteration": "ir"},
                {"hebrew": "רְחוֹב", "english": "street", "transliteration": "rechov"},
                {"hebrew": "כִּכָּר", "english": "square/plaza", "transliteration": "kikar"},
                {"hebrew": "בֵּית חוֹלִים", "english": "hospital", "transliteration": "beit cholim"},
                {"hebrew": "בֵּית סֵפֶר", "english": "school", "transliteration": "beit sefer"},
                {"hebrew": "אוּנִיבֶרְסִיטָה", "english": "university", "transliteration": "universita"},
                {"hebrew": "בַּנְק", "english": "bank", "transliteration": "bank"},
                {"hebrew": "בֵּית כְּנֶסֶת", "english": "synagogue", "transliteration": "beit knesset"},
                {"hebrew": "מִסְעָדָה", "english": "restaurant", "transliteration": "mis'ada"},
                {"hebrew": "בֵּית קָפֶה", "english": "cafe", "transliteration": "beit kafe"},
                {"hebrew": "פַּארְק", "english": "park", "transliteration": "park"},
                {"hebrew": "מוּזֵיאוֹן", "english": "museum", "transliteration": "muzeon"},
                {"hebrew": "קוֹלְנוֹעַ", "english": "cinema", "transliteration": "kolno'a"},
                {"hebrew": "תַּחֲנָה", "english": "station", "transliteration": "tachana"},
                {"hebrew": "שׁוּק", "english": "market", "transliteration": "shuk"},
                {"hebrew": "שָׁדֵה תְּעוּפָה", "english": "airport", "transliteration": "sde te'ufa"},
                {"hebrew": "מַלּוֹן", "english": "hotel", "transliteration": "malon"},
                {"hebrew": "סִפְרִיָּה", "english": "library", "transliteration": "sifriya"},
                {"hebrew": "דּוֹאַר", "english": "post office/mail", "transliteration": "do'ar"},
                {"hebrew": "מִשְׂרָד", "english": "office", "transliteration": "misrad"},
            ],
            "directions": [
                {"hebrew": "אֵיפֹה", "english": "where", "transliteration": "eifo"},
                {"hebrew": "פֹּה", "english": "here", "transliteration": "po"},
                {"hebrew": "שָׁם", "english": "there", "transliteration": "sham"},
                {"hebrew": "יָמִין", "english": "right", "transliteration": "yamin"},
                {"hebrew": "שְׂמֹאל", "english": "left", "transliteration": "smol"},
                {"hebrew": "יָשָׁר", "english": "straight", "transliteration": "yashar"},
                {"hebrew": "קָרוֹב", "english": "close/near", "transliteration": "karov"},
                {"hebrew": "רָחוֹק", "english": "far", "transliteration": "rachok"},
                {"hebrew": "צָפוֹן", "english": "north", "transliteration": "tzafon"},
                {"hebrew": "דָּרוֹם", "english": "south", "transliteration": "darom"},
                {"hebrew": "מִזְרָח", "english": "east", "transliteration": "mizrach"},
                {"hebrew": "מַעֲרָב", "english": "west", "transliteration": "ma'arav"},
                {"hebrew": "כִּיוּוּן", "english": "direction", "transliteration": "kivun"},
                {"hebrew": "מַפָּה", "english": "map", "transliteration": "mapa"},
                {"hebrew": "סְלִיחָה אֵיפֹה", "english": "excuse me where", "transliteration": "slicha eifo"},
                {"hebrew": "רוֹצֶה לָלֶכֶת", "english": "want to go (m)", "transliteration": "rotze lalechet"},
                {"hebrew": "רוֹצָה לָלֶכֶת", "english": "want to go (f)", "transliteration": "rotza lalechet"},
                {"hebrew": "בְּסֵדֶר תּוֹדָה", "english": "okay thanks", "transliteration": "beseder toda"},
                {"hebrew": "כְּתֹבֶת", "english": "address", "transliteration": "ktovet"},
                {"hebrew": "מָקוֹם", "english": "place", "transliteration": "makom"},
            ],

            # Course 10: Basic Verbs
            "to-be-to-have": [
                {"hebrew": "הָיָה", "english": "was/were (m)", "transliteration": "haya"},
                {"hebrew": "הָיְתָה", "english": "was/were (f)", "transliteration": "hayta"},
                {"hebrew": "יֵשׁ", "english": "there is/have", "transliteration": "yesh"},
                {"hebrew": "אֵין", "english": "there isn't/don't have", "transliteration": "ein"},
                {"hebrew": "יֵשׁ לִי", "english": "I have", "transliteration": "yesh li"},
                {"hebrew": "אֵין לִי", "english": "I don't have", "transliteration": "ein li"},
                {"hebrew": "הוּא", "english": "he", "transliteration": "hu"},
                {"hebrew": "הִיא", "english": "she", "transliteration": "hi"},
                {"hebrew": "אֲנַחְנוּ", "english": "we", "transliteration": "anachnu"},
                {"hebrew": "אַתֶּם", "english": "you (m pl)", "transliteration": "atem"},
                {"hebrew": "אַתֶּן", "english": "you (f pl)", "transliteration": "aten"},
                {"hebrew": "הֵם", "english": "they (m)", "transliteration": "hem"},
                {"hebrew": "הֵן", "english": "they (f)", "transliteration": "hen"},
                {"hebrew": "זֶה", "english": "this is (m)", "transliteration": "ze"},
                {"hebrew": "זֹאת", "english": "this is (f)", "transliteration": "zot"},
            ],
            "want-need-can": [
                {"hebrew": "רוֹצֶה", "english": "want (m)", "transliteration": "rotze"},
                {"hebrew": "רוֹצָה", "english": "want (f)", "transliteration": "rotza"},
                {"hebrew": "צָרִיךְ", "english": "need (m)", "transliteration": "tzarich"},
                {"hebrew": "צְרִיכָה", "english": "need (f)", "transliteration": "tzricha"},
                {"hebrew": "יָכוֹל", "english": "can (m)", "transliteration": "yachol"},
                {"hebrew": "יְכוֹלָה", "english": "can (f)", "transliteration": "yechola"},
                {"hebrew": "מוּכְרָח", "english": "must (m)", "transliteration": "muchrach"},
                {"hebrew": "מוּכְרַחַת", "english": "must (f)", "transliteration": "muchrachat"},
                {"hebrew": "אֶפְשָׁר", "english": "possible/may", "transliteration": "efshar"},
                {"hebrew": "אִי אֶפְשָׁר", "english": "impossible", "transliteration": "i efshar"},
                {"hebrew": "מַמָּשׁ", "english": "really/very", "transliteration": "mamash"},
                {"hebrew": "קְצָת", "english": "a little", "transliteration": "ktzat"},
                {"hebrew": "הַרְבֵּה", "english": "a lot", "transliteration": "harbe"},
                {"hebrew": "בְּכְלָל לֹא", "english": "not at all", "transliteration": "bichlal lo"},
                {"hebrew": "גַּם", "english": "also", "transliteration": "gam"},
            ],
        }

        for lesson_id, vocab in lesson_vocab.items():
            lesson = await prisma.lesson.find_unique(where={"id": lesson_id})
            if lesson:
                await prisma.lesson.update(
                    where={"id": lesson_id},
                    data={"vocabulary": json.dumps(vocab)}
                )
                print(f"[OK] Updated {lesson_id} with {len(vocab)} words")
            else:
                print(f"[SKIP] Lesson {lesson_id} not found")

        print(f"\n[SUCCESS] Updated {len(lesson_vocab)} lessons with real vocabulary!")

    finally:
        await prisma.disconnect()

if __name__ == "__main__":
    asyncio.run(main())
